name: kids_app
description: Kids task manager
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  get: ^4.6.5
  provider: ^6.0.2
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  pluto_grid: ^8.0.0
  uuid: ^4.3.3
  go_router: ^14.1.3
  path_provider: ^2.0.14
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.0
  intl: ^0.19.0
  file_picker: ^8.1.3

  # from Google Fonts
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1

#  ftl_flutter_uikit:
#    path: ../../ftl_flutter_uikit
#  ftl_marketing_flutter_lib:
#    path: ../../ftl_marketing_flutter_lib
#  ftl_flutter_shell_lib:
#    path: ../../ftl_flutter_shell_lib
#  ftl_flutter_authorization:
#    path: ../../ftl_flutter_authorization
#  ftl_flutter_core_lib:
#    path: ../../ftl_flutter_core_lib


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.4.0
  flutter_native_splash: ^2.4.0
  icons_launcher: ^3.0.0
  rename: ^3.0.2

flutter:
  uses-material-design: true

#  assets:
#    - assets/
#    - assets/logo/logo.png
#    - assets/logo/logo_ios.png
#    - assets/logo/logo_rounded.png
#    - assets/splash/logo_splash.png

#flutter_native_splash:
#  image: assets/splash/logo_splash.png
#  color: "#FFDB3A"
#  android: true
#  ios: true
#  android_12:
#    image: assets/splash/logo_splash.png


#icons_launcher:
#  image_path: "assets/logo/logo.png"
#  platforms:
#    android:
#      enable: true
#      adaptive_round_image: "assets/logo/logo_rounded.png"
#    ios:
#      enable: true
#      image_path: "assets/logo/logo_ios.png"
#    web:
#      enable: true
